// <auto-generated />
using System;
using GymManagementSystem.Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymManagementSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260216153433_RefreshToken")]
    partial class RefreshToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.ClassBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ScheduledClassId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ScheduledClassId");

                    b.ToTable("ClassBookings");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("HasParentalConsent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.ClientMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<int>("MembershipStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("MembershipId");

                    b.ToTable("ClientMemberships");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientMembershipId")
                        .HasColumnType("uuid");

                    b.Property<int>("ContractStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("IsSigned")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientMembershipId")
                        .IsUnique();

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContractTypeEnum")
                        .HasColumnType("integer");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MonthlySalaryBrutto")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.EmploymentTermination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("EmploymentTerminations");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.GeneralGymDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AboutUs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("interval");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DefaultGroupClassRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DefaultRate120")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DefaultRate60")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DefaultRate90")
                        .HasColumnType("numeric");

                    b.Property<string>("GymName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("interval");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GeneralGymDetails");

                    b.HasData(
                        new
                        {
                            Id = new Guid("65893784-da50-4c63-ae01-9704c5d5eda3"),
                            AboutUs = "We are a place created for people who want to truly improve their health, physique, and well-being — not just “tick off” a workout. Our goal is to build a strong, capable, and mindful community where everyone, regardless of their level, feels welcome. We combine modern equipment with expert coaching to make training not only hard, but smart. We focus on quality of movement, steady progress, and safety, because long-term results matter more than quick fixes. We help our members set clear goals and achieve them step by step.\r\n\r\nWe don’t believe in shortcuts — we believe in building lasting habits and real lifestyle change. We create an environment where training becomes part of everyday life, not a burden. We believe that a strong body builds a strong mind. That’s why we support, motivate, and educate — not just count reps. Our gym is more than equipment; it’s people, atmosphere, and a shared drive to be better than yesterday.",
                            Address = "123 Fitness St, Muscle City",
                            BackgroundColor = "#363740",
                            CloseTime = new TimeSpan(0, 22, 0, 0, 0),
                            ContactNumber = "123456789",
                            DefaultGroupClassRate = 60m,
                            DefaultRate120 = 150m,
                            DefaultRate60 = 100m,
                            DefaultRate90 = 120m,
                            GymName = "NextLevelGym",
                            LogoUrl = "http://localhost:5105/uploads/logos/logo_d8faf809-8917-4ddd-b78e-618df23cf5c8.png",
                            Nip = "123456789",
                            OpenTime = new TimeSpan(0, 7, 0, 0, 0),
                            PrimaryColor = "#EEEEEE",
                            SecondColor = "#9AAD00"
                        });
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.GymClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DaysOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxPeople")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("StartHour")
                        .HasColumnType("interval");

                    b.Property<Guid>("TrainerContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TrainerContractId");

                    b.ToTable("GymClasses");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ClassBookingDaysInAdvanceCount")
                        .HasColumnType("integer");

                    b.Property<int>("FreeFriendEntryCountPerMonth")
                        .HasColumnType("integer");

                    b.Property<int>("MembershipType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Memberships");

                    b.HasData(
                        new
                        {
                            Id = new Guid("18ec8725-c23b-4ea4-90d4-2952e3b110a0"),
                            ClassBookingDaysInAdvanceCount = 7,
                            FreeFriendEntryCountPerMonth = 3,
                            MembershipType = 0,
                            Name = "Silver Membership"
                        },
                        new
                        {
                            Id = new Guid("bedd6962-6fa4-435d-8505-b7c6092b9875"),
                            ClassBookingDaysInAdvanceCount = 14,
                            FreeFriendEntryCountPerMonth = 6,
                            MembershipType = 0,
                            Name = "Gold Membership"
                        },
                        new
                        {
                            Id = new Guid("62dd1607-fd54-4186-b282-8ef9d82cddcf"),
                            ClassBookingDaysInAdvanceCount = 7,
                            FreeFriendEntryCountPerMonth = 3,
                            MembershipType = 1,
                            Name = "Silver Membership"
                        },
                        new
                        {
                            Id = new Guid("db4a0dc9-6d66-445f-8ae1-e5b941e873cf"),
                            ClassBookingDaysInAdvanceCount = 14,
                            FreeFriendEntryCountPerMonth = 6,
                            MembershipType = 1,
                            Name = "Gold Membership"
                        });
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.MembershipFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FeatureDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.ToTable("MembershipFeatures");

                    b.HasData(
                        new
                        {
                            Id = new Guid("02ba27e2-0ee5-49ab-ba3d-345f21b3c385"),
                            FeatureDescription = "Full access to all training zones",
                            MembershipId = new Guid("18ec8725-c23b-4ea4-90d4-2952e3b110a0")
                        },
                        new
                        {
                            Id = new Guid("dc03e7b0-8815-49b5-a11a-5c0267807260"),
                            FeatureDescription = "Group classes included in the membership price",
                            MembershipId = new Guid("18ec8725-c23b-4ea4-90d4-2952e3b110a0")
                        },
                        new
                        {
                            Id = new Guid("bd98286f-0d46-4ccd-8ba4-41758a69ca8f"),
                            FeatureDescription = "Full access to all training zones",
                            MembershipId = new Guid("bedd6962-6fa4-435d-8505-b7c6092b9875")
                        },
                        new
                        {
                            Id = new Guid("ddbd8972-e04b-419e-91df-60e478a18b8a"),
                            FeatureDescription = "Group classes included in the membership price",
                            MembershipId = new Guid("bedd6962-6fa4-435d-8505-b7c6092b9875")
                        },
                        new
                        {
                            Id = new Guid("5d5c6e9d-f489-4d55-acdc-6027cd5571d6"),
                            FeatureDescription = "Full access to all training zones",
                            MembershipId = new Guid("62dd1607-fd54-4186-b282-8ef9d82cddcf")
                        },
                        new
                        {
                            Id = new Guid("e318bd2f-2d60-46f2-8ad7-10e1fc1fc0d9"),
                            FeatureDescription = "Group classes included in the membership price",
                            MembershipId = new Guid("62dd1607-fd54-4186-b282-8ef9d82cddcf")
                        },
                        new
                        {
                            Id = new Guid("e2c40d19-11e6-4f3e-82fa-786a2a54980a"),
                            FeatureDescription = "Full access to all training zones",
                            MembershipId = new Guid("db4a0dc9-6d66-445f-8ae1-e5b941e873cf")
                        },
                        new
                        {
                            Id = new Guid("23530b84-0153-4048-8471-9a37cf1f631d"),
                            FeatureDescription = "Group classes included in the membership price",
                            MembershipId = new Guid("db4a0dc9-6d66-445f-8ae1-e5b941e873cf")
                        },
                        new
                        {
                            Id = new Guid("67184db6-ecb1-41cd-9acb-f6aedd665acc"),
                            FeatureDescription = "Can book group classes up to 7 days in advance",
                            MembershipId = new Guid("18ec8725-c23b-4ea4-90d4-2952e3b110a0")
                        },
                        new
                        {
                            Id = new Guid("bb5f7ba8-2983-4671-ba86-ab1cb1e7c6d5"),
                            FeatureDescription = "Can invite a friend 3 times per month",
                            MembershipId = new Guid("18ec8725-c23b-4ea4-90d4-2952e3b110a0")
                        },
                        new
                        {
                            Id = new Guid("6ac75645-311b-4a21-bfa0-a1d63241d4ee"),
                            FeatureDescription = "Includes 1 free personal training session every 6 months",
                            MembershipId = new Guid("18ec8725-c23b-4ea4-90d4-2952e3b110a0")
                        },
                        new
                        {
                            Id = new Guid("be096096-e23e-4d58-bda5-029c8e548d60"),
                            FeatureDescription = "Can book group classes up to 14 days in advance",
                            MembershipId = new Guid("bedd6962-6fa4-435d-8505-b7c6092b9875")
                        },
                        new
                        {
                            Id = new Guid("6ed15175-5258-4610-a22b-e97644e16335"),
                            FeatureDescription = "Can invite a friend 6 times per month",
                            MembershipId = new Guid("bedd6962-6fa4-435d-8505-b7c6092b9875")
                        },
                        new
                        {
                            Id = new Guid("8e4665b9-e4a8-4e6d-a99e-0269ad7f97e8"),
                            FeatureDescription = "Includes 2 free personal training sessions every 6 months",
                            MembershipId = new Guid("bedd6962-6fa4-435d-8505-b7c6092b9875")
                        },
                        new
                        {
                            Id = new Guid("97ccec05-9a3d-4109-b8b2-74932d4f539b"),
                            FeatureDescription = "Can book group classes up to 7 days in advance",
                            MembershipId = new Guid("62dd1607-fd54-4186-b282-8ef9d82cddcf")
                        },
                        new
                        {
                            Id = new Guid("4ab370ee-5de7-4766-8f9d-4f330cc04224"),
                            FeatureDescription = "Can invite a friend 3 times per month",
                            MembershipId = new Guid("62dd1607-fd54-4186-b282-8ef9d82cddcf")
                        },
                        new
                        {
                            Id = new Guid("c4658526-88ba-4267-a1c9-e3d9619918a2"),
                            FeatureDescription = "Includes 1 free personal training session every 6 months",
                            MembershipId = new Guid("62dd1607-fd54-4186-b282-8ef9d82cddcf")
                        },
                        new
                        {
                            Id = new Guid("fe954cb7-6e94-4618-8a1b-1df21bdecac4"),
                            FeatureDescription = "Can book group classes up to 14 days in advance",
                            MembershipId = new Guid("db4a0dc9-6d66-445f-8ae1-e5b941e873cf")
                        },
                        new
                        {
                            Id = new Guid("4ac113fb-a62b-4f26-89ce-db18b1b65c6b"),
                            FeatureDescription = "Can invite a friend 6 times per month",
                            MembershipId = new Guid("db4a0dc9-6d66-445f-8ae1-e5b941e873cf")
                        },
                        new
                        {
                            Id = new Guid("aa87c5b9-9d57-4693-b607-618d34bc76ee"),
                            FeatureDescription = "Includes 2 free personal training sessions every 6 months",
                            MembershipId = new Guid("db4a0dc9-6d66-445f-8ae1-e5b941e873cf")
                        });
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.MembershipPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LabelPrice")
                        .HasColumnType("text");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.ToTable("MembershipPrices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d29e7b7-a940-4187-8a74-76ba99af8b1f"),
                            MembershipId = new Guid("18ec8725-c23b-4ea4-90d4-2952e3b110a0"),
                            Price = 100m,
                            ValidFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("1260207e-c0e3-4503-bb31-a5ef13e5cee8"),
                            MembershipId = new Guid("bedd6962-6fa4-435d-8505-b7c6092b9875"),
                            Price = 150m,
                            ValidFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f23a5317-8f53-4fc2-bfba-661728098038"),
                            MembershipId = new Guid("62dd1607-fd54-4186-b282-8ef9d82cddcf"),
                            Price = 1000m,
                            ValidFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("6707ecbd-f2c1-49ee-ae24-8ce497a4f501"),
                            MembershipId = new Guid("db4a0dc9-6d66-445f-8ae1-e5b941e873cf"),
                            Price = 1500m,
                            ValidFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("IdentityUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.PersonalBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrainerContractId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TrainerProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TrainerRateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("TrainerContractId");

                    b.HasIndex("TrainerProfileId");

                    b.HasIndex("TrainerRateId");

                    b.ToTable("PersonalBookings");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.ScheduledClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GymClassId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxPeople")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartFrom")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("StartTo")
                        .HasColumnType("interval");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GymClassId");

                    b.ToTable("ScheduledClasses");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.Termination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientMembershipId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientMembershipId")
                        .IsUnique();

                    b.ToTable("Terminations");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.TrainerContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ClubCommissionPercent")
                        .HasColumnType("numeric");

                    b.Property<int>("ContractType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TrainerProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("TrainerType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasIndex("TrainerProfileId");

                    b.ToTable("TrainerContracts");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.TrainerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("TrainerProfiles");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.TrainerRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("RatePerSessions")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TrainerContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TrainerContractId");

                    b.ToTable("TrainerRates");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.TrainerTimeOff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TrainerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainerTimeOff");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientMembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("GuestName")
                        .HasColumnType("text");

                    b.Property<bool>("IsWithGuest")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VisitSource")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.ClassBooking", b =>
                {
                    b.HasOne("GymManagementSystem.Core.Domain.Entities.Client", "Client")
                        .WithMany("ClassBookings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManagementSystem.Core.Domain.Entities.ScheduledClass", "ScheduledClass")
                        .WithMany("ClassBookings")
                        .HasForeignKey("ScheduledClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ScheduledClass");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.ClientMembership", b =>
                {
                    b.HasOne("GymManagementSystem.Core.Domain.Entities.Client", "Client")
                        .WithMany("ClientMemberships")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManagementSystem.Core.Domain.Entities.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.Contract", b =>
                {
                    b.HasOne("GymManagementSystem.Core.Domain.Entities.ClientMembership", "ClientMembership")
                        .WithOne("Contract")
                        .HasForeignKey("GymManagementSystem.Core.Domain.Entities.Contract", "ClientMembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientMembership");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.Employee", b =>
                {
                    b.HasOne("GymManagementSystem.Core.Domain.Entities.Person", "Person")
                        .WithOne("Employee")
                        .HasForeignKey("GymManagementSystem.Core.Domain.Entities.Employee", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.EmploymentTermination", b =>
                {
                    b.HasOne("GymManagementSystem.Core.Domain.Entities.Person", "Person")
                        .WithMany("EmploymentTerminations")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.GymClass", b =>
                {
                    b.HasOne("GymManagementSystem.Core.Domain.Entities.TrainerContract", "Trainer")
                        .WithMany("GymClasses")
                        .HasForeignKey("TrainerContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.MembershipFeature", b =>
                {
                    b.HasOne("GymManagementSystem.Core.Domain.Entities.Membership", "Membership")
                        .WithMany("MembershipFeatures")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.MembershipPrice", b =>
                {
                    b.HasOne("GymManagementSystem.Core.Domain.Entities.Membership", "Membership")
                        .WithMany("MembershipPrices")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.PersonalBooking", b =>
                {
                    b.HasOne("GymManagementSystem.Core.Domain.Entities.Client", "Client")
                        .WithMany("PersonalBookings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManagementSystem.Core.Domain.Entities.TrainerContract", "TrainerContract")
                        .WithMany("PersonalBookings")
                        .HasForeignKey("TrainerContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManagementSystem.Core.Domain.Entities.TrainerProfile", null)
                        .WithMany("PersonalBookings")
                        .HasForeignKey("TrainerProfileId");

                    b.HasOne("GymManagementSystem.Core.Domain.Entities.TrainerRate", "TrainerRate")
                        .WithMany()
                        .HasForeignKey("TrainerRateId");

                    b.Navigation("Client");

                    b.Navigation("TrainerContract");

                    b.Navigation("TrainerRate");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.ScheduledClass", b =>
                {
                    b.HasOne("GymManagementSystem.Core.Domain.Entities.GymClass", "GymClass")
                        .WithMany("ScheduledClasses")
                        .HasForeignKey("GymClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GymClass");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.Termination", b =>
                {
                    b.HasOne("GymManagementSystem.Core.Domain.Entities.ClientMembership", "ClientMembership")
                        .WithOne("Termination")
                        .HasForeignKey("GymManagementSystem.Core.Domain.Entities.Termination", "ClientMembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientMembership");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.TrainerContract", b =>
                {
                    b.HasOne("GymManagementSystem.Core.Domain.Entities.Person", "Person")
                        .WithOne("TrainerContract")
                        .HasForeignKey("GymManagementSystem.Core.Domain.Entities.TrainerContract", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManagementSystem.Core.Domain.Entities.TrainerProfile", "TrainerProfile")
                        .WithMany()
                        .HasForeignKey("TrainerProfileId");

                    b.Navigation("Person");

                    b.Navigation("TrainerProfile");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.TrainerRate", b =>
                {
                    b.HasOne("GymManagementSystem.Core.Domain.Entities.TrainerContract", "TrainerContract")
                        .WithMany("Rates")
                        .HasForeignKey("TrainerContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainerContract");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.TrainerTimeOff", b =>
                {
                    b.HasOne("GymManagementSystem.Core.Domain.Entities.TrainerContract", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.Visit", b =>
                {
                    b.HasOne("GymManagementSystem.Core.Domain.Entities.Client", "Client")
                        .WithMany("Visits")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Identity.User", b =>
                {
                    b.HasOne("GymManagementSystem.Core.Domain.Entities.Client", null)
                        .WithOne("User")
                        .HasForeignKey("GymManagementSystem.Core.Domain.Identity.User", "ClientId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("GymManagementSystem.Core.Domain.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GymManagementSystem.Core.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GymManagementSystem.Core.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("GymManagementSystem.Core.Domain.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymManagementSystem.Core.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GymManagementSystem.Core.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.Client", b =>
                {
                    b.Navigation("ClassBookings");

                    b.Navigation("ClientMemberships");

                    b.Navigation("PersonalBookings");

                    b.Navigation("User");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.ClientMembership", b =>
                {
                    b.Navigation("Contract");

                    b.Navigation("Termination");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.GymClass", b =>
                {
                    b.Navigation("ScheduledClasses");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.Membership", b =>
                {
                    b.Navigation("MembershipFeatures");

                    b.Navigation("MembershipPrices");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.Person", b =>
                {
                    b.Navigation("Employee");

                    b.Navigation("EmploymentTerminations");

                    b.Navigation("TrainerContract");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.ScheduledClass", b =>
                {
                    b.Navigation("ClassBookings");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.TrainerContract", b =>
                {
                    b.Navigation("GymClasses");

                    b.Navigation("PersonalBookings");

                    b.Navigation("Rates");
                });

            modelBuilder.Entity("GymManagementSystem.Core.Domain.Entities.TrainerProfile", b =>
                {
                    b.Navigation("PersonalBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
